version : '3'
services :
    db:
        container_name: db
        image: postgres:10.16
        environment:
            POSTGRES_USER : hamonize
            POSTGRES_PASSWORD : password
            POSTGRES_DB : hamonize_center
            TZ : "Asia/Seoul"
        ports:
            - "5435:5432"
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
            - psql-data:/var/lib/postgresql/data
        restart: always
           
volumes:
    psql-data:

